#!/bin/bash
# Script to deploy CredTech XScore application

set -e

# Default values
ENVIRONMENT="staging"
DEPLOYMENT_DIR="/opt/credtech-xscore"
IMAGE_TAG="latest"

# Parse command line arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --environment|-e)
      ENVIRONMENT="$2"
      shift 2
      ;;
    --dir|-d)
      DEPLOYMENT_DIR="$2"
      shift 2
      ;;
    --tag|-t)
      IMAGE_TAG="$2"
      shift 2
      ;;
    --help|-h)
      echo "Usage: $0 [--environment|-e <environment>] [--dir|-d <deployment_directory>] [--tag|-t <image_tag>]"
      echo "  --environment, -e: Environment to deploy to (staging or production). Default: staging"
      echo "  --dir, -d: Directory to deploy to. Default: /opt/credtech-xscore"
      echo "  --tag, -t: Docker image tag to deploy. Default: latest"
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      exit 1
      ;;
  esac
done

echo "Deploying CredTech XScore to $ENVIRONMENT environment"
echo "Deployment directory: $DEPLOYMENT_DIR"
echo "Image tag: $IMAGE_TAG"

# Check if deployment directory exists
if [ ! -d "$DEPLOYMENT_DIR" ]; then
  echo "Error: Deployment directory does not exist"
  exit 1
fi

# Check if docker-compose.yml exists
if [ ! -f "$DEPLOYMENT_DIR/docker-compose.yml" ]; then
  echo "Error: docker-compose.yml not found in deployment directory"
  exit 1
fi

# Check if .env.deployment exists
if [ ! -f "$DEPLOYMENT_DIR/.env.deployment" ]; then
  echo "Error: .env.deployment not found in deployment directory"
  exit 1
fi

# Create .env file with registry and image information
cat > "$DEPLOYMENT_DIR/.env" << EOF
# Generated by deploy.sh on $(date)
REGISTRY=\${REGISTRY:-ghcr.io}
IMAGE_NAME=\${IMAGE_NAME:-credtech/credtech-xscore}
IMAGE_TAG=$IMAGE_TAG
EOF

# Merge .env.deployment with .env
cat "$DEPLOYMENT_DIR/.env.deployment" >> "$DEPLOYMENT_DIR/.env"

# Pull latest images
cd "$DEPLOYMENT_DIR"
echo "Pulling latest images..."
docker-compose pull

# Stop and remove existing containers
echo "Stopping existing containers..."
docker-compose down || true

# Start new containers
echo "Starting new containers..."
docker-compose up -d

# Clean up old images
echo "Cleaning up old images..."
docker system prune -af

echo "Deployment completed successfully"